# Generated by Django 3.0.7 on 2020-06-25 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipamento',
            name='item_unico',
        ),
        migrations.RemoveField(
            model_name='equipamento',
            name='quantidade',
        ),
        migrations.DeleteModel(
            name='Movimento',
        ),
    ]
