# Generated by Django 3.0.7 on 2020-06-29 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200625_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localizacao',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='localizacao',
            name='modificado_em',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
