# Generated by Django 3.0.7 on 2020-07-11 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200629_1535'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['nome'], 'verbose_name': 'categoria', 'verbose_name_plural': 'categorias'},
        ),
        migrations.AlterModelOptions(
            name='equipamento',
            options={'ordering': ['codigo', 'categoria', 'fabricante'], 'verbose_name': 'equipamento', 'verbose_name_plural': 'equipamentos'},
        ),
        migrations.AlterModelOptions(
            name='fabricante',
            options={'ordering': ['nome'], 'verbose_name': 'fabricante', 'verbose_name_plural': 'fabricantes'},
        ),
        migrations.AlterModelOptions(
            name='grupo',
            options={'ordering': ['nome'], 'verbose_name': 'grupo', 'verbose_name_plural': 'grupos'},
        ),
        migrations.AlterModelOptions(
            name='localizacao',
            options={'ordering': ['nome'], 'verbose_name': 'localização', 'verbose_name_plural': 'localizações'},
        ),
        migrations.AlterModelOptions(
            name='setor',
            options={'ordering': ['nome'], 'verbose_name': 'setor', 'verbose_name_plural': 'setores'},
        ),
    ]
